use exams;
select job from emp;
select distinct job from emp;
select ename from emp where ename like 'j%';
select distinct job from emp where job like 's%';
select ename from emp where ename not like 'j%';
select ename from emp where ename like '%d';
select ename from emp where ename like '_____';
select ename from emp where ename like 'j%s';
select ename from emp where ename like 'j_m_s';
select ename from emp where ename like 'j___s';
select empno,ename,sal from emp where sal between 1500 and 2000;
select empno,ename,sal from emp where sal not between 1500 and 2000;
select empno,ename,sal from emp order by ename;
select empno,ename,sal from emp order by ename desc;
select empno,ename,sal from emp where deptno in (10,20) order by ename;
select empno,ename,sal from emp where deptno = 20 or deptno = 10 order by ename;
select empno,ename from emp where mgr is null;
select count(*),count(ename),count(sal) from emp;
select count(sal),sum(sal),avg(sal),max(sal),min(sal) from emp;
select  job , sum(sal) from emp group by job;
 select ename from emp where sal = (select max(sal) from emp);
 select e1.empno,el.sal from emp e1 where e1.sal in (select e2.sal from emp e2  where e2.deptno = 10);
 select ename from emp where exists (select * from emp);